language: python

os:
  - linux

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - make
  - bin/pip3 install pytest-random-order

script:
  - PYTHONPATH=$PWD:$PYTHONPATH bin/py.test -m 'not ignore' --random-order-bucket=global tests

notifications:
  email: false